### ISSUE TITLE
DB Scheme not updated.

### ISSUE THREAD

**Issue by sylkat** [asoltys/coinos-server#7]
I am getting an error when i start the backend server related to db:

**Unknown column 'invoices_model.unconfidential' in 'field list'**

I guess is related to the schema.sql provided in the Readme is not updated and synced against the code in git.

Can you provide an updated schema.sql or in case i am wrong a clue?

Thanks

**Comment by sylkat** [comment]
Well the schema.sql only lack 2 fields:

1 in invoices table:
`unconfidential` varchar(255) NOT NULL,
1 in users table:
`fiat` boolean DEFAULT NULL,

Regards,

**Comment by asoltys** [comment]
Hi, sorry about that, I've updated the schema now: https://github.com/asoltys/coinos-server/commit/4e506759982cfb9d725dc807966833cf7f02e1d2
